import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {mkdtemp,mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import express from 'express';
import Stripe from 'stripe';
import type {Database} from '../server/database.js';
import {migrate} from '../server/database.js';
import {PersistentSessions,accountRoutes,importLegacy,account} from '../server/accounts.js';
import {recordAttempt,listeningRoutes} from '../server/attempts.js';
import {backup,restore} from '../server/backups.js';
import {recoveryRoutes} from '../server/recovery.js';
import {billingRoutes,aiQuota,premium} from '../server/billing.js';
import {isListeningAnswerCorrect} from '../src/utils/listeningGrading.js';

async function local(directory:string):Promise<Database>{const p=new PGlite(directory);await p.waitReady;return {query:(sql,args)=>p.query(sql,args),transaction:fn=>p.transaction(fn),close:()=>p.close()};}

test('durable transactions, replay prevention, recovery, webhook signatures and backup restoration',async()=>{
  await mkdir('.codex-tmp/tests',{recursive:true});
  const root=await mkdtemp(path.resolve('.codex-tmp/tests/architecture-'));
  let db=await local(path.join(root,'source'));
  await migrate(db);
  await db.query("INSERT INTO accounts(id,email,username,profile) VALUES('alice','alice@example.test','alice','{}')");
  let sessions=new PersistentSessions(db);
  const token=await sessions.create('alice');
  const result={totalScore:30,maxScore:30};
  const submitted=await Promise.all(Array.from({length:6},()=>recordAttempt(db,'alice','attempt-one','listening','track-one','input-one',result,45)));
  assert.equal(submitted.reduce((n,r)=>n+r.awarded,0),45);
  assert.equal((await account(db,'alice')).listening_done,1);
  await assert.rejects(recordAttempt(db,'alice','attempt-one','listening','track-one','changed',result,45),/ID percubaan/);
  assert.equal((await recordAttempt(db,'alice','attempt-two','listening','track-one','input-two',result,45)).awarded,0);
  await db.close();
  db=await local(path.join(root,'source'));sessions=new PersistentSessions(db);
  assert.equal(await sessions.get(token),'alice','session survives a database restart');
  assert.equal((await account(db,'alice')).points,45);

  process.env.APP_URL='http://127.0.0.1:3000';
  process.env.STRIPE_WEBHOOK_SECRET='whsec_test_fixture';process.env.STRIPE_PRICE_ID='price_fixture';
  process.env.FREE_AI_DAILY_LIMIT='2';
  const stripe=new Stripe('sk_test_fixture');
  let active=true;
  (stripe.subscriptions as any).retrieve=async()=>({id:'sub_fixture',status:active?'active':'canceled',metadata:{userId:'alice'},items:{data:[{price:{id:'price_fixture'},current_period_end:Math.floor(Date.now()/1000)+86400}]}});
  const {router,auth}=accountRoutes(db,sessions);
  const billing=billingRoutes(db,auth,stripe);
  const sent:string[]=[];
  const app=express();app.use(billing.webhook);app.use(express.json());app.use(router);app.use(billing.router);
  app.use(recoveryRoutes(db,async(_email,link)=>{sent.push(link);}));app.use(listeningRoutes(db,auth));
  app.get('/quota',auth,aiQuota(db),(_req,res)=>res.json({ok:true}));
  app.use(((error:any,_req:any,res:any,_next:any)=>res.status(error.status||500).json({error:error.message})) as express.ErrorRequestHandler);
  const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));
  const address=server.address() as any;
  const request=(route:string,body?:any,authToken=token)=>fetch(`http://127.0.0.1:${address.port}${route}`,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${authToken}`},body:body===undefined?undefined:JSON.stringify(body)});
  try{
    const checkins=await Promise.all(Array.from({length:5},()=>request('/progress/check-in',{}).then(r=>r.json())));
    assert.equal(checkins.reduce((n,r)=>n+r.awarded,0),20,'parallel daily claims award once');
    assert.equal((await account(db,'alice')).points,65);
    await request('/auth/sync-progress',{points:999999,lastSpmGrade:{grade:'A+'}});
    assert.equal((await account(db,'alice')).points,65,'client points ignored');
    const answers={'q-1-1':'B. 25,000 orang murid','q-1-2':'15,000','q-1-3':true};
    const listening=await request('/attempts/listening',{attemptId:'12345678-1234-1234-1234-123456789012',trackId:'dengar-1',answers});
    const graded=await listening.json();assert.equal(graded.correctCount,3);assert.equal(graded.awarded,45);
    assert.equal((await request('/quota')).status,200);assert.equal((await request('/quota')).status,200);assert.equal((await request('/quota')).status,429);
    const event={id:'evt_active',type:'customer.subscription.updated',data:{object:{id:'sub_fixture'}}};
    const payload=JSON.stringify(event);
    const postEvent=(payload:string,signature:string)=>fetch(`http://127.0.0.1:${address.port}/billing/webhook`,{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':signature},body:payload});
    assert.equal((await postEvent(payload,'forged')).status,400);
    assert.equal(await premium(db,'alice'),false);
    const sign=(payload:string)=>stripe.webhooks.generateTestHeaderString({payload,secret:'whsec_test_fixture'});
    assert.equal((await postEvent(payload,sign(payload))).status,200);
    assert.equal((await postEvent(payload,sign(payload))).status,200);
    assert.equal(await premium(db,'alice'),true);
    assert.equal((await db.query('SELECT * FROM payment_events')).rows.length,1);
    active=false;const canceled=JSON.stringify({...event,id:'evt_canceled',type:'customer.subscription.deleted'});
    await postEvent(canceled,sign(canceled));assert.equal(await premium(db,'alice'),false);
    const delayed=JSON.stringify({...event,id:'evt_delayed'});await postEvent(delayed,sign(delayed));assert.equal(await premium(db,'alice'),false,'delayed active event uses current provider state');
    assert.equal((await request('/auth/forgot-password',{email:'missing@example.test'})).status,202);
    assert.equal(sent.length,0);
    await request('/auth/forgot-password',{email:'alice@example.test'});assert.equal(sent.length,1);
    const resetToken=new URL(sent[0]).searchParams.get('reset');
    assert.equal((await request('/auth/reset-password',{token:resetToken,password:'new-password-long'})).status,200);
    assert.equal(await sessions.get(token),undefined,'reset revokes all sessions');
    assert.equal((await request('/auth/reset-password',{token:resetToken,password:'another-password-long'})).status,400);
  }finally{await new Promise<void>(r=>server.close(()=>r()));}
  const filename=path.join(root,'backup.json');
  const before=await backup(db,filename);assert.equal(before.accounts,1);
  await assert.rejects(restore(db,filename),/empty target/);
  const snapshotPoints=(await account(db,'alice')).points;
  const conflicting=path.join(root,'conflict.json');
  await writeFile(conflicting,JSON.stringify([{id:'new-one',username:'one',email:'same@example.test'},{id:'new-two',username:'two',email:'same@example.test'}]));
  await assert.rejects(importLegacy(db,conflicting));
  assert.equal((await db.query('SELECT * FROM accounts')).rows.length,1,'failed import rolls back every row');
  await db.close();
  db=await local(path.join(root,'restored'));await migrate(db);
  await restore(db,filename);
  assert.equal((await account(db,'alice')).points,snapshotPoints);
  assert.equal((await db.query('SELECT * FROM attempts')).rows.length,before.attempts);
  const altered=path.join(root,'corrupt.json'), envelope=JSON.parse(await readFile(filename,'utf8'));envelope.payload+='x';await writeFile(altered,JSON.stringify(envelope));
  await assert.rejects(restore(db,altered),/checksum/);
  await db.close();
});

test('listening comparator preserves decimal meaning and valid thousands',()=>{
  const q={type:'fill_blank',correctAnswer:'15,000'};
  assert.equal(isListeningAnswerCorrect('15000',q),true);
  assert.equal(isListeningAnswerCorrect('15k',q),true);
  assert.equal(isListeningAnswerCorrect('15',q),false);
  assert.equal(isListeningAnswerCorrect('15.000',q),false);
  assert.equal(isListeningAnswerCorrect('15000abc',q),false);
  assert.equal(isListeningAnswerCorrect('1.5',{type:'fill_blank',correctAnswer:'15'}),false);
});
